AWSTemplateFormatVersion: '2010-09-09'
Description: Kittens Carousel Static Website Deployment

Parameters:
  HostedZoneName:
    Description: The DNS name of an existing Amazon Route 53 hosted zone (e.g., clarusway.us)
    Type: AWS::Route53::HostedZone::Id

  DomainName:
    Description: The full domain name for the web application (e.g., kittens.clarusway.us)
    Type: AWS::Route53::HostedZone::Id

Resources:
  KittensAppBuckettx:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensAppBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref KittensAppBuckettx
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${KittensAppBuckettx}/*

  KittensCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Kittens Carousel Distribution
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt KittensAppBuckettx.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:487583754392:certificate/88f655a4-1ed0-4bed-8419-5fc8a636d59b
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
          

Outputs:
  KittensDomainName:
    Description: Full Domain Name of Kittens Carousel Application
    Value: !Ref DomainName

  KittensCloudFrontEndpoint:
    Description: Endpoint for Kittens CloudFront Distribution
    Value: !GetAtt KittensCloudFrontDistribution.DomainName
