AWSTemplateFormatVersion: '2010-09-09'
Description: Kittens Carousel Static Website Deployment

Parameters:
  HostedZoneName:
    Description: The DNS name of an existing Amazon Route 53 hosted zone (e.g., clarusway.us)
    Type: String

  DomainName:
    Description: The full domain name for the web application (e.g., kittens.clarusway.us)
    Type: String

  ExistingS3Bucket:
    Description: The name of the existing S3 bucket to use for the website
    Type: String

  AcmCertificateArn:
    Description: The ARN of the ACM certificate to use for securing connections
    Type: String

Resources:
  KittensS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ExistingS3Bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  KittensCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Kittens Carousel Distribution
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt KittensS3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only

  KittensRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: Kittens Carousel Record Set
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt KittensCloudFrontDistribution.DomainName

Outputs:
  KittensDomainName:
    Description: Full Domain Name of Kittens Carousel Application
    Value: !Ref DomainName

  KittensCloudFrontEndpoint:
    Description: Endpoint for Kittens CloudFront Distribution
    Value: !GetAtt KittensCloudFrontDistribution.DomainName

  KittensS3BucketName:
    Description: Name of S3 Bucket for Kittens Website
    Value: !Ref ExistingS3Bucket
